### ISSUE TITLE
WSL 里运行的 Redis 无法测试连接，无法保存，必须要输入密码？

### ISSUE THREAD

**Issue by KISSMonX** [Kuari/MyRedisDesktopManager#2]
![image](https://user-images.githubusercontent.com/2876745/178290121-6a98c3b9-4c5f-4cf9-bfa6-618c6650cd23.png)

**Comment by winjeg** [comment]
你的邮箱可用么？

**Comment by hunter-ji** [comment]
> ![image](https://user-images.githubusercontent.com/2876745/178290121-6a98c3b9-4c5f-4cf9-bfa6-618c6650cd23.png)

你好，多谢反馈！

不是必须要输入密码的，如果测试连接不通，那应该就是连接不上redis server。

**Comment by Kuari** [comment]
> 你的邮箱可用么？有兴趣聊聊么，我不是猎头, 也不是给你推荐工作的。
你好，邮箱是可用的。

**Comment by hunter-ji** [comment]
> 你的邮箱可用么？有兴趣聊聊么，我不是猎头, 也不是给你推荐工作的。

你好，邮箱是可用的。
