### ISSUE TITLE
长 json 展示不完

### ISSUE THREAD

**Issue by Attiv** [Kuari/MyRedisDesktopManager#3]
窗口越大展示的越多，不能滚到底

**Comment by Kuari** [comment]
> 窗口越大展示的越多，不能滚到底

多谢反馈，将在下一版本中更新。

**Comment by hunter-ji** [comment]
> 窗口越大展示的越多，不能滚到底

你好，请问方便截个图吗？我测试了一下，目前没有重现这个问题。

**Comment by Attiv** [comment]
> > 窗口越大展示的越多，不能滚到底
> 
> 你好，请问方便截个图吗？我测试了一下，目前没有重现这个问题。

我不太方便把数据截图发出来，之前刚发生过安全问题，抱歉。您可以找个很长的json 放进去，60+行，一个屏幕显示不完，滚动不到底

**Comment by hunter-ji** [comment]
> 

好的，请问是右键打开json的那个数据放大弹窗那里吗？

**Comment by Attiv** [comment]
是的，格式化显示 json 那

**Comment by hunter-ji** [comment]
👌 我来复现处理一下，多谢反馈！

**Comment by hunter-ji** [comment]
嗨，最新版本v1.0.2已经发布，长json问题也已解决，多谢反馈！🎉
