### ISSUE TITLE
数据库点击保存,测试链接没反应

### ISSUE THREAD

**Issue by podigua** [Kuari/MyRedisDesktopManager#5]
数据库点击保存,测试链接没反应,根本没法用呀兄弟

**Comment by hunter-ji** [comment]
你好，保存没有变化应该就是数据库没脸接上。在保存之前会有一次ping请求，确保数据库的连接成功，成功后，才改变连接状态且保存完成。
<img width="1149" alt="image" src="https://user-images.githubusercontent.com/25321169/188783248-df85a3a7-a142-4743-9112-ce7270ef5bbe.png">

**Comment by hunter-ji** [comment]
下一版本我会改进下这块的交互/抱拳
